= Ng Jin - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com/CS2103AUG2017-F10-B3/main/blob/master/collated/main/Labradorites.md] [https://github.com/CS2103AUG2017-F10-B3/main/blob/master/collated/test/Labradorites.md] {give links to collated code files}

=== Enhancement Added: findPhone
Finds persons whose phones contain any of the given keywords.
This search function is able to take in more than 1 keyword by separating each of them with a space.
Person whose number contains any of the keyword
* findPhone 000
Returns 10001 and 191000
* find 111 222 333
Returns any person having phone numbers 1111, 0222, or 9333
==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=undoredo]

#End of Extract#

---

==== Justification

Allowing the user to search for his contacts by phone introduces more flexibility and user-friendliness of AddressBook.
User's friend may have received a call from a phone number that is unsaved.
Hence with findPhone, user is able to help check if the number happens to be in his AddressBook.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=undoredo]

#End of Extract#

---

=== Enhancement Added: findTag
Finds persons whose tags contain any of the given keywords.
This search function is able to take in more than 1 keyword by separating each of them with a space.
Person whose tags contains any of the keyword
* findTag friends
  Returns friends
*findTag friends family neighbours
 Returns any person having tags friends, family, or neighbour
==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=undoredo]

#End of Extract#

---

==== Justification

Allowing the user to search for his contacts by tags introduces more flexibility and user-friendliness of AddressBook.
User is able to filter and see his a group of his contact that are of the same tag which he can then use for relating people or to mass send messages by groups.
Hence with findPhone, user is able to help check if the number happens to be in his AddressBook.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=undoredo]

#End of Extract#

---

=== Enhancement Added: listTags [f]
Lists unique tags in AddressBook by preference. List of tags is displayed in ResultsBox.
*  `listTags` lists all unique tags added to AddressBook.
* `listTags f` displays unique list of tags of persons currently displayed in the PersonListPanel.
==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=undoredo]

#End of Extract#

---

==== Justification

Allowing the user to list tags in 2 ways introduces more flexibility and user-friendliness of AddressBook.
With listTags, user can see all tags that he has added to AddressBook and can refer to his old tags if he wants to reuse the same name.
With listTags f, user is able to filter and see a range of tags which he can then use for relating people.
Hence with findPhone, user is able to help check if the number happens to be in his AddressBook.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=undoredo]

#End of Extract#

---

=== Enhancement Proposed: -


=== Other contributions


== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
