= Ng Ki Kan - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: FindEmail

==== External behavior

---
Finds persons whose email contain any of the given keywords. +
Format: `findEmail KEYWORD`

****
* The search is case insensitive. e.g. `hans` will match `Hans`
* Partial word can also be searched. e.g. `john` will match `johndoe@example.com`
* Only the email is searched.
****

Examples:

* `findEmail jane` +
Returns `janedoe@example.com`

---

==== Justification

From time to time, we will receive email from unknown email address. This feature comes in handy to look up if it is from a friend.

==== Implementation

---
The find email mechanism is facilitated by regex. After finding matches, result will be stored in the filtered list that is showing on the UI.
Further improvement might include allowing user to use flag(e.g. findEmail \f KEYWORD) to do advance search.

---

=== Enhancement Added: ChangeTheme

==== External behavior

---
Change the UI theme through command or UI
Command Format: `theme light/dark`
UI: click "File > ____ theme"

---

==== Justification

Address book is a personal application. By allowing user to change the color theme to meet their need, an more intimate connection is formed and it increases app sticky.

==== Implementation

---
The change theme mechanism is implemented in both command and GUI level. By typing command `theme light/dark` or clicking the menu item "Dark theme" or "Light theme", it triggers an internal function "setTheme" and change the theme accordingly.

---

=== Enhancement Proposed: Add command OutputCSV



=== Other contributions

* Updated the GUI color scheme
